import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { AirtableApiTypes } from './404';

const Home: NextPage = ({ records }: any) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {records?.map((row: any) => (
          <div key={row.id}>
            <Image layout="fill" alt="zainus" src={row.fields.Photos[0].url} />
          </div>
        ))}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export async function getStaticProps() {
  const response = await fetch(`${process.env.AIRTABLE_API_URL}${process.env.AIRTABLE_PHOTOS}`, {
    method: 'GET',
    headers: {
      Authorization: `${process.env.AIRTABLE_API_KEY}`,
    },
  });
  const res: AirtableApiTypes = await response.json();

  return {
    props: {
      records: res.records,
    },
  };
}

export default Home;
